channels:
  - conda-forge
  - defaults
  - bioconda
dependencies:
  - numpy
  - scipy
  - cython
  - matplotlib
  - pandas
  - h5py
  - numba<0.44.1
  - dask
  - scikit-learn
  - cooler
  - click
  - pytest
